server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/restaurantequis;
    index index.html;

    location /docs {
        proxy_pass         http://backend:5000/docs;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
    }

    location /openapi.json {
        proxy_pass         http://backend:5000/openapi.json;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
    }

    location /api/ {
        proxy_pass         http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
